//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchung
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public long PlatzNr { get; set; }
        public System.Guid VorfuehrungID { get; set; }
    
        public virtual Vorfuehrung Vorfuehrung { get; set; }
    }
}
